### ISSUE TITLE
Ambient Light Template/Macro cannot be changed and save

### ISSUE THREAD

**Issue by Streyder** [flamewave000/dragonflagon-arch#113]
Hi,

if I open an ambient light template/macro and  change the name the changes are not saved to the macro.
Upon opening the light template this error occurs:
```

foundry.js:316 TypeError: app.object.getFlag is not a function
[Detected 1 package: levels]
    at config.js:399:35
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at AmbientLightConfig._render (foundry.js:3114:13)
    at async AmbientLightConfig._render (foundry.js:3761:5)
```

Once I try to save my changes the following error occur:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'checked')
[Detected 2 packages: perfect-vision, lib-wrapper]
    at AmbientLightConfig.<anonymous> (config.js:1083:70)
    at AmbientLightConfig.wrapper (patch.js:17:25)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:619:16)
    at AmbientLightConfig.🎁AmbientLightConfig.prototype._getSubmitData#0 (libWrapper-wrapper.js:188:20)
    at AmbientLightConfig._onChangeInput (foundry.js:54055:30)
```

```
config.js:1083 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'checked')
[Detected 2 packages: perfect-vision, lib-wrapper]
    at AmbientLightConfig.<anonymous> (config.js:1083:70)
    at AmbientLightConfig.wrapper (patch.js:17:25)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:619:16)
    at AmbientLightConfig.🎁AmbientLightConfig.prototype._getSubmitData#0 (libWrapper-wrapper.js:188:20)
    at AmbientLightConfig._onSubmit (foundry.js:3840:27)
```
The changes made are not updated in the the template.

If any more info is required, please let me know.

Cheers

**Comment by flamewave000** [comment]
I'm not sure if you're still having this issue, but I am unable to reproduce it. I also have Perfect Vision enabled without issue. The only thing that might be a conflict is the Levels module since that's in one of your errors, otherwise I'm not sure.

**Comment by Streyder** [comment]
This seems fixed in the current version.

**Comment by Streyder** [comment]
Seems fixed in the current version.
