### ISSUE TITLE
Module DF Architect LbWrapperPackageError

### ISSUE THREAD

**Issue by Bluzpicker** [flamewave000/dragonflagon-arch#136]
**Following is the Error text I copied from the browser console:**

df-architect.ts:110 LibWrapperPackageError: Error detected in module DF Architect.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/flamewave000/dragonflagon-arch
Report this issue here: https://github.com/flamewave000/dragonflagon-arch/issues/new/choose

== Technical Details:
Detected by libWrapper.
Package ID= df-architect
Error= Could not find target 'BackgroundLayer.prototype.activate': Could not find root scope 'BackgroundLayer'.

[Detected 1 package: df-architect]
    at ae (libWrapper-api.js:135:10)
    at se (libWrapper-api.js:152:19)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at TileCounter.ready (TileCounter.ts:8:14)
    at Object.fn (df-architect.ts:110:8)

**Comment by Bluzpicker** [comment]
This issue had been reported by a different user. Sorry.
