### ISSUE TITLE
V11 compatibility

### ISSUE THREAD

**Issue by apoapostolov** [flamewave000/dragonflagon-arch#170]
```
foundry.js:753 TypeError: Failed drawing interface canvas group: this._getWallColor is not a function. this._getWallColor is not a function
[Detected 3 packages: df-architect, lib-wrapper, monks-tokenbar]
    at Wall._onWallDraw (WallDirections.ts:62:15)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Wall.prototype.draw#0 (libWrapper-wrapper.js:189:20)
    at foundry.js:34691:18
    at EmbeddedCollection.map (commons.js:4191:26)
    at WallsLayer._draw (foundry.js:34688:32)
    at WallsLayer._draw (foundry.js:42195:17)
    at WallsLayer.draw (foundry.js:34194:16)
    at async InterfaceCanvasGroup.draw (foundry.js:28972:9)
    at async InterfaceCanvasGroup.draw (foundry.js:47329:5)
    at async Canvas.draw (foundry.js:26135:9)
    at async Scene.view (foundry.js:23275:7)
    at async Scene.sceneView (monks-tokenbar.js:168:20)
    at async Game.initializeCanvas (foundry.js:8789:20)
    at async Game.setupGame (foundry.js:8623:5)
    at async Game._initializeGameView (foundry.js:9881:5)
    at async Game.initialize (foundry.js:8544:5)
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
draw @ foundry.js:26137
await in draw (async)
view @ foundry.js:23275
🎁call_wrapped @ libWrapper-wrapper.js:507
sceneView @ monks-tokenbar.js:168
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Scene.prototype.view#0 @ libWrapper-wrapper.js:189
initializeCanvas @ foundry.js:8789
await in initializeCanvas (async)
setupGame @ foundry.js:8618
await in setupGame (async)
_initializeGameView @ foundry.js:9881
_initializeView @ foundry.js:9857
initialize @ foundry.js:8544
await in initialize (async)
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁libWrapperInit @ libWrapper-api.js:805
await in 🎁libWrapperInit (async)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:90096
foundry.js:67285 Failed drawing interface canvas group: this._getWallColor is not a function
```

**Comment by be221b** [comment]
Wondering if this module is abandoned?

**Comment by coffiarts** [comment]
So it seems so to me.

Even more, looking at the discussions around the other open issues, I get the impression that migrating this module to v11 might be a tough nut. This mod overrides - by design -  some basic UI functionality of Foundry, and it appears that v11, by design, now prohibits such oversteering. At least in some of the aspects (whereas some of them might still work).

So someone would have to sort out what _is_ still supported and what###  isn't, then at least remove all the now _unsupported_ functions, update the docs, repackage the whole thing etc.

**Comment by RavenknightDM** [comment]
Think I will remain with 10 for the time being. DF's modules are far too good to skip.

**Comment by flamewave000** [comment]
Does not support v11. Currently working on v12 support.
