### ISSUE TITLE
DF Architect - Can't wrap 'AmbientLight.prototype._drawControlIcon', target does not exist or could not be found.

### ISSUE THREAD

**Issue by rafacrudi** [flamewave000/dragonflagon-arch#171]
Shows on console, once loading DF Architect module.
Using v11.302 with D&D 2.2.1

LibWrapperPackageError: lib-wrapper. Error detected in module DF Architect. It is likely this module has not been updated for FVTT Version 11 Stable.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/flamewave000/dragonflagon-arch
Report this issue here: https://github.com/flamewave000/dragonflagon-arch/issues/new/choose

== Technical Details:
Detected by libWrapper.
Package ID= df-architect
Error= Can't wrap 'AmbientLight.prototype._drawControlIcon', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, df-architect]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at AltLightOrigin.init (AltLightOrigin.ts:24:14)
    at Object.fn (df-architect.ts:55:8)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8573:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
(anonymous) @ df-architect.ts:55

**Comment by coffiarts** [comment]
The root cause here is that it tries to register function "_drawControlIcon" from AmbientLight (with the goal to override it), but this method has been declared private in Foundry v11 and isn't accessible anymore.
I am currently trying to understand it a bit better from the migration guides at https://foundryvtt.com/article/migration/
My worst assumption is that, what DF architect has been doing here in v10, isn't possible anymore in v11. But we'll see...
